# CUDA_VISIBLE_DEVICES=1 python src/lerobot/scripts/lerobot_train.py \
#   --dataset.root=/media/raid/workspace/tengbo/any4lerobot/data/lerobot_data/InterceptGrabMedium-v0/mikasa_dataset_1.0.0_lerobot \
#   --dataset.repo_id=JackYuuuu/InterceptGrabMedium-v0 \
#   --policy.repo_id=JackYuuuu/act_policy_v0 \
#   --policy.type=act \
#   --output_dir=outputs/train/Act_InterceptGrabMedium-v0\
#   --job_name=Act_InterceptGrabMedium-v0 \
#   --policy.device=cuda \
#   --wandb.enable=true

CUDA_VISIBLE_DEVICES=3 python src/lerobot/scripts/lerobot_train.py \
  --dataset.root=/media/raid/workspace/tengbo/any4lerobot/data/lerobot_data/InterceptGrabMedium-v0/mikasa_dataset_1.0.0_lerobot \
  --dataset.repo_id=JackYuuuu/InterceptGrabMedium-v0 \
  --policy.repo_id=JackYuuuu/Groot_InterceptGrabMedium_100 \
  --policy.type=groot \
  --output_dir=outputs/train/Groot_InterceptGrabMedium-v0\
  --job_name=Groot_InterceptGrabMedium-v0 \
  --policy.device=cuda \
  --wandb.enable=true